Repository knowledgesystems/knowledgesystems-k8s-deployment, pull requests merged in 2020-04, with the labels that each got.

#69 Updates that correspond with moving mongo to 4.0.12
  cronjob/genie_gn_weekly_mongodump.yaml
  cronjob/gn_weekly_mongodump.yaml
  genome-nexus/README.md
  genome-nexus/mongo/genie_gn_mongo_pvc.yaml
  genome-nexus/mongo/genie_gn_mongodump_pvc.yaml
  genome-nexus/mongo/helm/mongo_default_config.yaml
  genome-nexus/mongo/public_gn_mongo_pvc.yaml
  genome-nexus/mongo/public_gn_mongodump_pvc.yaml
Labels: bug

#58 Modify cache setup to work with latest VEP wrapper
  genome-nexus/vep/gn_vep.yaml
Labels: DO NOT MERGE

#61 Config Updates for GENIE
  genome-nexus/gn_genie.yaml
  genome-nexus/vep/genie_gn_vep.yaml
  genome-nexus/vep/gn_vep_pv.yaml
  genome-nexus/vep/gn_vep_pvc.yaml
Labels: DO NOT MERGE

#72 follow-up fixes to genie configurations
  genome-nexus/gn_genie.yaml
  genome-nexus/vep/genie_gn_vep.yaml
  genome-nexus/vep/gn_vep.yaml
  genome-nexus/vep/gn_vep_pv.yaml
Labels: enhancement
